-- ---------------------------------------------------------------------------
-- EKOLI YEDEN DIGITAL HOME — Migration 0001
-- Identity, authorisation and site settings.
--
-- Every table uses a TEXT primary key generated by the Worker, and every
-- timestamp is an ISO-8601 string in UTC. SQLite has no native boolean, so
-- flags are INTEGER 0/1 with a CHECK constraint.
-- ---------------------------------------------------------------------------

-- --------------------------------------------------------------------------
-- users
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                          TEXT PRIMARY KEY,
  email                       TEXT NOT NULL UNIQUE,
  display_name                TEXT NOT NULL,
  -- PBKDF2-SHA256, derived in the Worker. NULL for accounts created by an
  -- administrator that have not yet set a password.
  password_hash               TEXT,
  password_salt               TEXT,
  avatar_media_id             TEXT,
  phone                       TEXT,
  bio                         TEXT,
  -- Position within the Ekoli-Yeden Preservation Team. Describes what the
  -- volunteer does; platform permissions come from user_roles.
  preservation_team_position  TEXT,
  status                      TEXT NOT NULL DEFAULT 'active'
                                CHECK (status IN ('active', 'invited', 'suspended')),
  email_verified_at           TEXT,
  last_login_at               TEXT,
  created_at                  TEXT NOT NULL,
  updated_at                  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_position ON users (preservation_team_position);

-- --------------------------------------------------------------------------
-- roles
--
-- `permissions` is a JSON array of "<resource>:<action>" strings. Super Admin
-- holds the single wildcard "*".
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id           TEXT PRIMARY KEY,
  slug         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  description  TEXT,
  permissions  TEXT NOT NULL DEFAULT '[]',
  -- System roles are seeded by migration and must not be deleted, or the
  -- community could lock itself out of its own archive.
  is_system    INTEGER NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1)),
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);

-- --------------------------------------------------------------------------
-- user_roles
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_roles (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role_id     TEXT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  assigned_by TEXT REFERENCES users (id) ON DELETE SET NULL,
  created_at  TEXT NOT NULL,
  UNIQUE (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles (role_id);

-- --------------------------------------------------------------------------
-- sessions
--
-- Only a digest of the refresh token is stored, so a database snapshot cannot
-- be replayed as a live session. Revoking a row ends the session immediately,
-- before the access token would otherwise expire.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  refresh_token_hash  TEXT NOT NULL,
  user_agent          TEXT,
  -- Salted digest of the IP address, never the address itself.
  ip_hash             TEXT,
  expires_at          TEXT NOT NULL,
  revoked_at          TEXT,
  created_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions (expires_at);

-- --------------------------------------------------------------------------
-- site_settings
--
-- Values an administrator can change without a deployment. Keys are created by
-- migration so the client always knows what it may receive; the admin API
-- changes values only.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  value_type  TEXT NOT NULL DEFAULT 'string'
                CHECK (value_type IN ('string', 'number', 'boolean', 'json')),
  group_name  TEXT NOT NULL DEFAULT 'general',
  -- Only rows flagged public are returned by GET /api/settings.
  is_public   INTEGER NOT NULL DEFAULT 1 CHECK (is_public IN (0, 1)),
  description TEXT,
  updated_at  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_site_settings_group ON site_settings (group_name);

-- --------------------------------------------------------------------------
-- audit_logs
--
-- Append-only. Because this platform is meant to be an authoritative community
-- record, every content change, moderation decision and role change is written
-- here. There is deliberately no UPDATE or DELETE path in the application.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  id             TEXT PRIMARY KEY,
  actor_id       TEXT REFERENCES users (id) ON DELETE SET NULL,
  actor_email    TEXT,
  action         TEXT NOT NULL,
  resource_type  TEXT,
  resource_id    TEXT,
  changes        TEXT,
  ip_hash        TEXT,
  user_agent     TEXT,
  request_id     TEXT,
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON audit_logs (resource_type, resource_id);
